# .goreleaser.dev.yaml
version: 2

project_name: prometheus-cli

release:
  disable: true

builds:
  - id: prometheus-cli-dev
    goos:
      - linux
    goarch:
      - amd64
    binary: "prom-cli"
    main: "."
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.revision={{.Commit}}"
      - "-X main.branch={{.Branch}}"
      - "-X main.buildUser={{.Env.BUILD_USER}}"
      - "-X main.buildDate={{.Env.BUILD_DATE}}"
      - "-X 'main.goVersion={{.Env.GO_VERSION}}'"
      - "-X main.projectURL=https://github.com/SckyzO/prometheus-cli"
    env:
      - CGO_ENABLED=0

archives:
  - id: prometheus-cli-dev-archive
    name_template: "{{ .ProjectName }}.dev"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

signs:
  - artifacts: checksum