# .goreleaser.yaml
version: 2

project_name: prometheus-cli

# Release configuration
release:
  github:
    owner: sckyzo
  name_template: "{{ .ProjectName }} v{{ .Version }}"

builds:
  - id: prometheus-cli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    binary: "prom-cli"
    main: "."
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.revision={{.Commit}}"
      - "-X main.branch={{.Branch}}"
      - "-X main.buildUser={{.Env.BUILD_USER}}"
      - "-X main.buildDate={{.Env.BUILD_DATE}}"
      - "-X 'main.goVersion={{.Env.GO_VERSION}}'"
      - "-X main.projectURL=https://github.com/SckyzO/prometheus-cli"
    env:
      - CGO_ENABLED=0

archives:
  - id: prometheus-cli-release-archive
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"